-- KLE Tech Digital Credential System Database Schema
-- ONEST Network Compliant
-- STRICT IMPLEMENTATION
-- Note: Mapped AUTOINCREMENT to SERIAL/INTEGER GENERATED BY DEFAULT AS IDENTITY for PostgreSQL compatibility.

DROP TABLE IF EXISTS MARKS;
DROP TABLE IF EXISTS STUDENT_COURSE;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS FACULTY;
DROP TABLE IF EXISTS STUDENT;

-- STUDENT Table
CREATE TABLE STUDENT (
    student_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    date_of_birth DATE,
    enrollment_date DATE,
    department VARCHAR(100),
    batch_year INTEGER,
    division VARCHAR(50),
    section VARCHAR(50),
    course_enrolled VARCHAR(100),
    current_semester INTEGER,
    password_dob VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FACULTY Table
CREATE TABLE FACULTY (
    faculty_id VARCHAR(50) PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    department VARCHAR(100),
    designation VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COURSE Table
CREATE TABLE COURSE (
    course_id VARCHAR(50) PRIMARY KEY,
    course_code VARCHAR(50) UNIQUE NOT NULL,
    course_name VARCHAR(200) NOT NULL,
    department VARCHAR(100),
    credits INTEGER,
    semester INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- STUDENT_COURSE Table
CREATE TABLE STUDENT_COURSE (
    id SERIAL PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    enrollment_date DATE,
    status VARCHAR(50) DEFAULT 'enrolled',
    FOREIGN KEY (student_id) REFERENCES STUDENT(student_id),
    FOREIGN KEY (course_id) REFERENCES COURSE(course_id),
    UNIQUE(student_id, course_id)
);

-- MARKS Table
CREATE TABLE MARKS (
    marks_id SERIAL PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    semester INTEGER,
    marks_obtained DECIMAL(5,2),
    max_marks DECIMAL(5,2),
    grade VARCHAR(10),
    exam_date DATE,
    exam_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES STUDENT(student_id),
    FOREIGN KEY (course_id) REFERENCES COURSE(course_id)
);